version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=designia_db
    ports:
      - '5432:5432'
    volumes:
      - 'designia-db-data:/var/lib/postgresql/data'

volumes:
  designia-db-data: {}